WIP HOTT-2352: Added table to display additional code and duty
trade-tariff/trade-tariff-frontend pull request #1293
Opened 2023-01-27 14:28 UTC by maverickvi

### Jira link

[HOTT-<TODO>](https://transformuk.atlassian.net/browse/HOTT-2352)

### What?

I have added/removed/altered:

- [ ] Added table to display additional code and duty

### Why?

I am doing this because:

- this will help users understand which code belongs to a duty

2023-01-30 19:21 UTC, willfish commented on app/views/commodities/_commodity.html.erb
> +              <% tcd.each do |t| %>
```suggestion
              <% tcd.each do |m| %>
```

2023-01-31 17:06 UTC, jebw requested changes
Looks good but lets DRY out the css incase GovUK tweak things in the future :raised_hands:

2023-01-31 17:06 UTC, jebw commented on app/webpacker/src/stylesheets/_commodity-tree.scss
> +  font-size: 14px;
rather then duplicate govuk sizes, we should defer to them 
- see https://github.com/trade-tariff/trade-tariff-frontend/blob/main/app/webpacker/src/stylesheets/_commodity-codes.scss#L89

And for the margins
- https://design-system.service.gov.uk/styles/spacing/#applying-spacing-in-your-own-css

2023-02-02 09:38 UTC, jebw requested changes
Couple of suggestions for coding polish but the only detail I'm keen to see change is to remove the leading slash from the partial name

Not convinced this is actually a problem but seems better to stick to the standard convention

2023-02-02 09:38 UTC, jebw commented on app/views/commodities/_commodity.html.erb
> +            <%= render '/commodities/additional_code_table', measures: tcd %>
This should not require a leading slash - I'm not sure about when in a view (and obviously rendering a partial) but in a controller that actually refers to a specific template file rather a relative one

2023-02-02 09:38 UTC, jebw commented on app/views/commodities/_commodity.html.erb
> +          <% if tcd.count > 1 %>
This could be `if tcd.many?`, and the second one `tcd.any?`

2023-02-02 09:38 UTC, jebw commented on spec/views/commodities/_additional_code_table.html.erb_spec.rb
> +  let(:measure) { build :measure, :vat, :with_additional_code }
could use `build_list` here ?

```ruby
let(:measures) { build_list :measure, 2, :vat, :with_additional_code }
```

2023-02-02 16:17 UTC, jebw approved these changes
Approved - looks good, can you just remove the spurious `//here` you've added in `_commodity-tree.scss` before merging. Thanks

2023-02-06 16:07 UTC, merged