HOTT-2984:  Sanitise stop press titles and content titles
trade-tariff/trade-tariff-frontend pull request #1406
Opened 2023-04-04 13:32 UTC by maverickvi

### Jira link

https://transformuk.atlassian.net/browse/HOTT-2984

### What?

I have added/removed/altered:

- [x] Sanitised stop press titles and content titles

### Why?

I am doing this because:

- We want to escape dangerous html and allow safe html

### Have you? (optional)

<img width="962" alt="Screenshot 2023-04-04 at 14 31 13" src="https://user-images.githubusercontent.com/12201130/229809151-244fb576-c37f-41ea-879f-efea58618a77.png">

2023-04-04 13:53 UTC, jebw requested changes
Looks great, just a minor tweak for the factory changes

2023-04-04 13:53 UTC, jebw commented on spec/factories/news/item_factory.rb
> +      unsafe_html = "<script>alert('Hello, world!')</script>"
This isn't really needed and tbh I'm not entirely sure the scope these variables are getting set in - I think its fine to duplicate this short string in the content and title attributes

2023-04-04 13:53 UTC, jebw commented on spec/factories/news/item_factory.rb
> +      safe_html = '<abbr>MFN</abbr>'
Likewise I think this is a bit uncommon, I'd just copy the `safe_html` contents into the other two strings

2023-04-04 14:01 UTC, jebw approved these changes
LGTM :raised_hands:

2023-04-06 10:08 UTC, willfish requested changes
How comes so much is changing in this PR?

2023-04-12 09:57 UTC, maverickvi commented
> 

The issue with how Github was displaying commits has been resolved by their team.

2023-04-12 09:58 UTC, merged