HOTT-4344: How to page error fix
trade-tariff/trade-tariff-frontend pull request #1705
Opened 2023-11-07 17:34 UTC by maverickvi

### Jira link

https://transformuk.atlassian.net/browse/HOTT-4344

### What?

I have added/removed/altered:

- [ ] Fixed missing template error

### Why?

I am doing this because:

- we need to display 404 error when page is missing

2023-11-07 17:39 UTC, jebw requested changes, later dismissed
This will error if the user requests a format of html?

How about checking if its blank or html?

2023-11-07 17:45 UTC, willfish submitted a review, later dismissed

2023-11-08 16:03 UTC, willfish submitted a review, later dismissed

2023-11-08 16:14 UTC, willfish approved these changes

2023-11-08 16:21 UTC, merged