HOTT-5215: Add filtering the Goods Nomenclature page by geo area
trade-tariff/trade-tariff-frontend pull request #1853
Opened 2024-03-06 17:37 UTC by rasikasri

### Jira link

[HOTT-5215](https://transformuk.atlassian.net/browse/HOTT-5215)

### What?

I have added/removed/altered:

- [ ] Extend the green lanes goods nomenclature page to allow filtering by geographical area

### Why?

I am doing this because:

- User can choose country and feeding it into the api to filtering category assessment
-
-

### Have you? (optional)

- [ ] Reviewed view changes with stake holders
- [ ] Validated mobile responsive behaviour of view changes

2024-03-07 12:21 UTC, jebw requested changes
Looks great, can you add a screen grab to the PR and swap to using the formbuilder for the dropdown (it will generate the label as well), thanks :+1:

2024-03-07 12:21 UTC, jebw commented on app/views/green_lanes/category_assessments/show.html.erb
> +      <div class="govuk-fieldset search-submit">
Not sure what the search-submit is for _but_ if the formbuilder is used correctly we shouldn't need custom spacing

This might be because the earlier field isn't using the govuk formbuilders version of `select`

2024-03-07 12:21 UTC, jebw commented on app/views/green_lanes/category_assessments/show.html.erb
> +        <%= f.select :country, GeographicalArea.country_options, { include_blank: 'All countries' }, class: 'custom-select', "aria-label": "Filter measures by country" %>
Please use the govuk formbuilder helpers - means things like errors will show up correctly

https://govuk-form-builder.netlify.app/form-elements/select/

2024-03-07 12:21 UTC, jebw commented on app/views/green_lanes/category_assessments/show.html.erb
> +        <%= f.select :country, GeographicalArea.country_options, { include_blank: 'All countries' }, class: 'custom-select', "aria-label": "Filter measures by country" %>
I'm not sure what `custom-select` does but it in general custom classes should be avoided wherever possible

The design system combined with the formbuilder in theory should provide all the classes we need - there's always exceptions but the ideal is to try and avoid adding custom css

2024-03-07 12:21 UTC, jebw commented on app/views/green_lanes/category_assessments/show.html.erb
> +        <%= f.label :country, 'Select Country', class: 'govuk-label' %>
Might make more sense to call this origin, and have the attribute as 'Select Origin'

2024-03-07 16:22 UTC, rasikasri commented on app/views/green_lanes/category_assessments/show.html.erb
> +      <div class="govuk-fieldset search-submit">
Removed

2024-03-07 16:22 UTC, rasikasri commented on app/views/green_lanes/category_assessments/show.html.erb
> +        <%= f.select :country, GeographicalArea.country_options, { include_blank: 'All countries' }, class: 'custom-select', "aria-label": "Filter measures by country" %>
Using the form builder for select now

2024-03-07 16:23 UTC, rasikasri commented on app/views/green_lanes/category_assessments/show.html.erb
> +        <%= f.label :country, 'Select Country', class: 'govuk-label' %>
Done

2024-03-11 17:14 UTC, jebw approved these changes
LGTM - much cleaner using the govuk form builder methods :raised_hands:

2024-03-13 10:57 UTC, merged