GOV UK style for table.
trade-tariff/trade-tariff-frontend pull request #338
Opened 2021-10-22 11:38 UTC by alexdesi

### Jira link

### Why?
This PR

-[x] adds the table Caption tag and remove the headers for the tables
-[x] adds many GOV UK styles to the table
-[x] remove zebra-stripes style to the rows
-[x] remove highlight to table on onmouseover

2021-10-26 10:27 UTC, alexdesi commented
Before:
Stripes and highlight:
<img width="1172" alt="Screenshot 2021-10-26 at 11 22 32" src="https://user-images.githubusercontent.com/58971/138859960-a1d61f93-6d73-40e6-b950-7e1607e3967d.png">


After:
No stripes/highlight AND new Heading
<img width="1182" alt="Screenshot 2021-10-27 at 12 04 51" src="https://user-images.githubusercontent.com/58971/139054307-68b54be3-7253-4559-92c8-4a12b22c3899.png">

2021-10-27 11:25 UTC, jebw requested changes
Looks good but commented out CSS code should be removed

One query is I thought the font size was meant to be staying small?

2021-10-27 11:25 UTC, jebw commented on app/webpacker/src/stylesheets/_tables.scss
> +    /*font-size: 12px;*/
These shouldn't be commented out - if they are no-longer required they should be removed.

2021-10-27 11:25 UTC, jebw commented on app/webpacker/src/stylesheets/_tables.scss
> +    /*@media (min-width: $small-table-breakpoint) {
Again  - this commented out block should be removed

2021-10-27 11:29 UTC, jebw approved these changes
LGTM

2021-10-27 11:34 UTC, merged