HOTT-1194: Adds TariffDate ActiveModel::Type
trade-tariff/trade-tariff-frontend pull request #498
Opened 2021-12-09 15:14 UTC by willfish

### Jira link

https://transformuk.atlassian.net/browse/HOTT-1194

### What?

I have added/removed/altered:

- [x] Handle invalid dates during Date type casting more gracefully

### Why?

I am doing this because:

- This was meant to resolve our need for the sentry-rails monkey patch by
  removing `include ActiveRecord::AttributeAssignment` (having ActiveRecord
  loaded in the AST triggers preloading connections before sending telemetry
  as part of an optimisation for serializing ActiveRecord model instances) but
  unfortunately was not able to achieve this
- It does achieve a significant tidy up in the api of the ImportExportDate model
  however

2021-12-14 15:08 UTC, jebw requested changes
Code is a nice clean up but I'm getting an odd behaviour

Previously - changing to 30 Feb 2021 would result in a validation failure
Now - it just swaps back to todays date?

2021-12-14 16:43 UTC, willfish commented
Weird. I tested this with Madhu. Will have a play tomorrow

2021-12-15 13:02 UTC, jebw requested changes
This isn't letting me change either month or year? Day does work though?

Just silently fails and goes back to todays date?

2021-12-15 13:20 UTC, willfish commented
I can't reproduce that myself.

2021-12-15 15:29 UTC, willfish commented
Debugging this specific commodity https://dev.trade-tariff.service.gov.uk/commodities/2915704095 it doesn't exist on months earlier than December so changing the date causes a redirect to today when landing on the commodity show action

2021-12-24 10:21 UTC, jebw requested changes
Code looks great and works well. Can we get a simple spec for the type - eg just checking behaviour with valid and invalid dates

2022-01-05 10:02 UTC, jebw approved these changes
Looks great!

2022-01-05 11:55 UTC, merged