Bug fixes for the Check duties box.
trade-tariff/trade-tariff-frontend pull request #513
Opened 2021-12-14 13:16 UTC by alexdesi

### What?
Fix background color, commodity code and wording for the Check duties box.

### Jira link
HOTT-1158

2021-12-14 16:34 UTC, jebw approved these changes
LGTM

2021-12-14 16:49 UTC, willfish commented on spec/helpers/measures_helper_spec.rb
> +      instance_double('Declarable', commodity_code_for_check_duties_service: 'code_for_check_duties', code: 'code')
```suggestion
      build(:commodity, id: '98010000')
```

2021-12-14 16:49 UTC, willfish commented on spec/helpers/measures_helper_spec.rb
> +        expect(link).to include('pc=code_for_check_duties')
```suggestion
        expect(link).to include('pc=980100')
```

2021-12-14 16:50 UTC, willfish requested changes
Tiny tweak to integrate rather than mock

2021-12-15 10:10 UTC, willfish approved these changes

2021-12-15 10:10 UTC, alexdesi commented on spec/helpers/measures_helper_spec.rb
> +      instance_double('Declarable', commodity_code_for_check_duties_service: 'code_for_check_duties', code: 'code')
👍

2021-12-15 10:10 UTC, merged